test-nf1:
  build: ./containers/test-nf1
  container_name: "nf1"
  volumes:
    - ./nfsrc:/code
  net: "none"
  privileged: true

test-nf2:
  build: ./containers/test-nf2
  container_name: "nf2"
  volumes:
    - ./nfsrc:/code
  net: "none"
  privileged: true

test-nf3:
  build: ./containers/test-nf3
  container_name: "nf3"
  volumes:
    - ./nfsrc:/code
  net: "none"
  privileged: true

iptables:
  build: ./containers/iptables
  container_name: "iptables"
  volumes:
    - ./nfsrc:/code
    - ./containers/iptables/iptables:/etc/iptables
    - ./containers/iptables/scripts:/scripts
    - ./containers/iptables/log:/var/log/
  net: "none"
  privileged: true
  command:
    - /sbin/init
    - /scripts/run.sh

snort:
  build: ./containers/snort
  container_name: "snort"
  volumes:
    - ./containers/snort/log:/var/log/snort
  net: "none"
  privileged: true
  command:
    - /sbin/init
